service: code-real-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    NODE_ENV: production
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  api:
    handler: lambda-handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: "*"

package:
  patterns:
    - "!node_modules/.prisma/**"
    - "!node_modules/@prisma/engines/**"
    - "!tests/**"
    - "!test/**"
    - "!*.test.js"
    - "!*.spec.js"
    - "!.git/**"
    - "!.gitignore"
    - "!README.md"
    - "!serverless.yml"
    - "!.env*"
    - "!coverage/**"
    - "!.nyc_output/**"
