name: Deploy to AWS Lambda

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS Lambda
        run: |
          cd backend
          serverless deploy --verbose
        env:
          NODE_ENV: production
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Get deployment URL
        run: |
          cd backend
          echo "Deployment URL: $(serverless info --verbose | grep -o 'https://[^ ]*')" >> $GITHUB_STEP_SUMMARY
